plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.android)
}

android {
    namespace = "com.fanbox.wallpapermaker"
    compileSdk = 34

    defaultConfig {
        applicationId = "com.fanbox.wallpapermaker"
        minSdk = 24
        targetSdk = 34
        versionCode = 1
        versionName = "1.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
        vectorDrawables {
            useSupportLibrary = true
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = '1.8'
    }

    buildFeatures {
        compose true
    }

    composeOptions {
        kotlinCompilerExtensionVersion = '1.5.1'
    }

    packaging {
        resources {
            excludes += ['/META-INF/AL2.0', '/META-INF/LGPL2.1']
        }
    }
}

dependencies {
    implementation libs.androidx.core.ktx
    implementation libs.androidx.lifecycle.runtime.ktx
    implementation platform(libs.androidx.compose.bom)
    implementation libs.androidx.ui
    implementation libs.androidx.ui.graphics
    implementation libs.androidx.ui.tooling.preview
    implementation libs.androidx.material3
    implementation libs.androidx.appcompat
    implementation libs.material
    implementation libs.androidx.activity
    implementation libs.androidx.constraintlayout
    implementation libs.androidx.camera.core
    testImplementation libs.junit
    androidTestImplementation libs.androidx.junit
    androidTestImplementation libs.androidx.espresso.core
    implementation libs.androidx.activity.compose
    androidTestImplementation platform(libs.androidx.compose.bom)
    androidTestImplementation libs.androidx.ui.test.junit4
    debugImplementation libs.androidx.ui.tooling
    debugImplementation libs.androidx.ui.test.manifest

    // Kotlin 标准库
    implementation libs.kotlin.stdlib

    // Kotlin 协程
    implementation libs.kotlinx.coroutines.core
    implementation libs.kotlinx.coroutines.android

    // Gson
    implementation libs.converter.gson
    implementation libs.play.services.mlkit.subject.segmentation

    // ViewModel and LiveData
    implementation 'androidx.lifecycle:lifecycle-livedata:2.3.1'
    implementation 'androidx.lifecycle:lifecycle-viewmodel:2.3.1'

    //Glide
    implementation 'com.github.bumptech.glide:glide:4.12.0'


    implementation 'org.tensorflow:tensorflow-lite:2.13.0' // 或最新版本
    implementation 'org.tensorflow:tensorflow-lite-support:0.4.0' // 如果需要模型支持库
    // 如果需要 GPU Delegate 支持可另外添加
    implementation 'org.tensorflow:tensorflow-lite-gpu:2.13.0'


//    implementation("org.opencv:opencv:4.10.0")
//    // CameraX
//    implementation 'androidx.camera:camera-camera2:1.0.0-SNAPSHOT'
//    implementation 'androidx.camera:camera-lifecycle:1.0.0-SNAPSHOT'
//    implementation 'androidx.camera:camera-view:1.0.0-SNAPSHOT'
}
